name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  animated_text_kit: ^4.2.2
  firebase_core: ^2.4.0
  firebase_auth: ^4.2.3
  cloud_firestore: ^4.3.0
  modal_progress_hud_nsn: ^0.3.0
  flutter_form_builder: ^7.1.1
  form_builder_validators: ^8.1.0
  form_builder_extra_fields: ^7.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/